export const GET_ALL_CHANNELS = 'GET_ALL_CHANNELS';
export const TOGGLE_ACTIVE_SELECTION_THEME = 'TOGGLE_ACTIVE_SELECTION_THEME';
export const SET_SELECTED_CHANNELS_DATA = 'SET_SELECTED_CHANNELS_DATA';
export const CLEAR_SELECTED_CHANNELS_DATA = 'CLEAR_SELECTED_CHANNELS_DATA';